#ifndef _TINY_TINYPRODUCTIONTYPE_H
#define _TINY_TINYPRODUCTIONTYPE_H

namespace tiny {

enum TinyProductionType {
    Program1 = 0,
    Program2 = 1,
    FunctionDefinition1 = 2,
    FunctionDefinition2 = 3,
    Type1 = 4,
    Type2 = 5,
    ParameterList1 = 6,
    ParameterList2 = 7,
    Parameter1 = 8,
    Block1 = 9,
    Block2 = 10,
    StatementList1 = 11,
    StatementList2 = 12,
    Statement1 = 13,
    Statement2 = 14,
    OpenStatement1 = 15,
    OpenStatement2 = 16,
    OpenStatement3 = 17,
    CloseStatement1 = 18,
    CloseStatement2 = 19,
    CloseStatement3 = 20,
    SimpleStatement1 = 21,
    SimpleStatement2 = 22,
    SimpleStatement3 = 23,
    SimpleStatement4 = 24,
    SimpleStatement5 = 25,
    ReturnStatement1 = 26,
    ReturnStatement2 = 27,
    ExpressionStatement1 = 28,
    LocalVarDecl1 = 29,
    LocalVarDecl2 = 30,
    AssignStatement1 = 31,
    LValue1 = 32,
    LValue2 = 33,
    Expression1 = 34,
    LogicalOrExpression1 = 35,
    LogicalOrExpression2 = 36,
    LogicalAndExpression1 = 37,
    LogicalAndExpression2 = 38,
    EqualityExpression1 = 39,
    EqualityExpression2 = 40,
    EqualityExpression3 = 41,
    RelationalExpression1 = 42,
    RelationalExpression2 = 43,
    RelationalExpression3 = 44,
    RelationalExpression4 = 45,
    RelationalExpression5 = 46,
    AdditiveExpression1 = 47,
    AdditiveExpression2 = 48,
    AdditiveExpression3 = 49,
    MultiplicativeExpression1 = 50,
    MultiplicativeExpression2 = 51,
    MultiplicativeExpression3 = 52,
    MultiplicativeExpression4 = 53,
    PrimaryExpression1 = 54,
    PrimaryExpression2 = 55,
    PrimaryExpression3 = 56,
    PrimaryExpression4 = 57,
    PrimaryExpression5 = 58,
    PrimaryExpression6 = 59,
    PrimaryExpression7 = 60,
    CallExpression1 = 61,
    CallExpression2 = 62,
    ArgumentList1 = 63,
    ArgumentList2 = 64
};

}

#endif
